package vma 

STATS_STRING_ENABLED :: 1;
RECORDING_ENABLED :: 0;
VULKAN_VERSION :: 1002000;
DEDICATED_ALLOCATION :: 1;
BIND_MEMORY2 :: 1;
MEMORY_BUDGET :: 1;
BUFFER_DEVICE_ADDRESS :: 1;
MEMORY_PRIORITY :: 1;
EXTERNAL_MEMORY :: 1;
